apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-zrs
  namespace: azuredisk-lrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-nginx-zrs
  template:
    metadata:
      labels:
        app: deployment-nginx-zrs
    spec:
      containers:
      - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
        name: nginx-azuredisk
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        command:
          - "/bin/sh"
          - "-c"
          - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
        volumeMounts:
          - name: zrs-azure-disk
            mountPath: "/mnt/azuredisk"
            readOnly: false
      volumes:
      - name: zrs-azure-disk
        persistentVolumeClaim:
          claimName: azuredisk-test-premium-zrs-disk-pvc-cloning