apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk-test-premium-lrs-disk-sc
parameters:
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
